version: '3'
services:
  database:
    image: postgres:11.6-alpine
    container_name: ff-db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ff-db
    ports:
      - "5432:5432"
  redis:
    image: redis:6.0-rc1-alpine
    container_name: ff-cache
    ports:
      - "6379:6379"
  server:
    container_name: ff-api
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:4000'
    links:
      - database
      - redis
  client:
    container_name: ff-frontend
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '80:80'