query folders($data: FolderArgs!) {
  folders(input: $data) {
    id
    title
    creationTime
    updatedTime
    notes {
      id
      title
      body
      isPrivate
      creationTime
      updatedTime
      user {
        id
        username
        profileImage
      }
      references {
        id
        name
        position
      }
    }
  }
}

query folder($data: FolderArgs!) {
  folder(input: $data) {
    id
    title
    creationTime
    updatedTime
    notes {
      id
      title
      creationTime
      updatedTime
    }
  }
}
