query teams($data: TeamArgs!) {
  teams(input: $data) {
    id
    city
    nickname
    fullName
    abbreviation
    byeWeek
    logoUrl
    primaryColor
    secondaryColor
    conference
    division
    headCoach
    offensiveCoordinator
    defensiveCoordinator
    offensiveScheme
    defensiveScheme
    stats {
      id
      timeOfPossession
      year
      firstDowns
      firstDownsByRushing
      firstDownsByPassing
      plays
      yards
      yardsPerPlay
      touchdowns
      rushingAttempts
      rushingYards
      rushingYardsPerAttempt
      rushingTouchdowns
      passingAttempts
      passingCompletions
      passingYards
      passingYardsPerAttempt
      passingTouchdowns
      thirdDownPercentage
      redzoneAttempts
      turnovers
    }
    stadium {
      name
      type
      playingSurface
      city
      state
      country
    }
    standings {
      wins
      losses
      ties
      conferenceWins
      conferenceTies
      conferenceLosses
      divisionWins
      divisionTies
      divisionLosses
      winPercentage
    }
  }
}

query team($data: TeamArgs!) {
  team(input: $data) {
    id
    city
    nickname
    fullName
    abbreviation
    byeWeek
    logoUrl
    primaryColor
    secondaryColor
    conference
    division
    headCoach
    offensiveCoordinator
    defensiveCoordinator
    offensiveScheme
    defensiveScheme
    stats {
      id
      timeOfPossession
      year
      firstDowns
      firstDownsByRushing
      firstDownsByPassing
      plays
      yards
      yardsPerPlay
      touchdowns
      rushingAttempts
      rushingYards
      rushingYardsPerAttempt
      rushingTouchdowns
      passingAttempts
      passingCompletions
      passingYards
      passingYardsPerAttempt
      passingTouchdowns
      thirdDownPercentage
      redzoneAttempts
      turnovers
    }
    stadium {
      id
      name
      type
      playingSurface
      city
      state
      country
    }
    standings {
      wins
      losses
      ties
      conferenceWins
      conferenceTies
      conferenceLosses
      divisionWins
      divisionTies
      divisionLosses
      winPercentage
    }
  }
}
